//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysBot.Pokemon.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysBot.Pokemon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {
        ///  &quot;m_GameObject&quot;: {
        ///    &quot;m_FileID&quot;: 0,
        ///    &quot;m_PathID&quot;: 0
        ///  },
        ///  &quot;m_Enabled&quot;: 1,
        ///  &quot;m_Script&quot;: {
        ///    &quot;m_FileID&quot;: 0,
        ///    &quot;m_PathID&quot;: 5036064567846753479
        ///  },
        ///  &quot;m_Name&quot;: &quot;FieldEncountTable_d&quot;,
        ///  &quot;table&quot;: [
        ///    {
        ///      &quot;zoneID&quot;: 24,
        ///      &quot;encRate_gr&quot;: 0,
        ///      &quot;ground_mons&quot;: [
        ///        {
        ///          &quot;maxlv&quot;: 0,
        ///          &quot;minlv&quot;: 0,
        ///          &quot;monsNo&quot;: 0
        ///        },
        ///        {
        ///          &quot;maxlv&quot;: 0,
        ///          &quot;minlv&quot;: 0,
        ///          &quot;monsNo&quot;: 0
        ///        },
        ///        {
        ///          &quot;maxlv&quot;: 0,
        /// [stringa troncata]&quot;;.
        /// </summary>
        internal static string FieldEncountTable_d {
            get {
                return ResourceManager.GetString("FieldEncountTable_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {
        ///  &quot;m_GameObject&quot;: {
        ///    &quot;m_FileID&quot;: 0,
        ///    &quot;m_PathID&quot;: 0
        ///  },
        ///  &quot;m_Enabled&quot;: 1,
        ///  &quot;m_Script&quot;: {
        ///    &quot;m_FileID&quot;: 0,
        ///    &quot;m_PathID&quot;: 5036064567846753479
        ///  },
        ///  &quot;m_Name&quot;: &quot;FieldEncountTable_p&quot;,
        ///  &quot;table&quot;: [
        ///    {
        ///      &quot;zoneID&quot;: 24,
        ///      &quot;encRate_gr&quot;: 0,
        ///      &quot;ground_mons&quot;: [
        ///        {
        ///          &quot;maxlv&quot;: 0,
        ///          &quot;minlv&quot;: 0,
        ///          &quot;monsNo&quot;: 0
        ///        },
        ///        {
        ///          &quot;maxlv&quot;: 0,
        ///          &quot;minlv&quot;: 0,
        ///          &quot;monsNo&quot;: 0
        ///        },
        ///        {
        ///          &quot;maxlv&quot;: 0,
        /// [stringa troncata]&quot;;.
        /// </summary>
        internal static string FieldEncountTable_p {
            get {
                return ResourceManager.GetString("FieldEncountTable_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Jubilife City
        ///Canalave City
        ///Canalave City
        ///Canalave Gym
        ///Canalave City
        ///Canalave City
        ///Canalave City
        ///Canalave City
        ///Canalave City
        ///Canalave City
        ///Canalave City
        ///Can [stringa troncata]&quot;;.
        /// </summary>
        internal static string text_bdsp_00000_en {
            get {
                return ResourceManager.GetString("text_bdsp_00000_en", resourceCulture);
            }
        }
    }
}
