namespace SysBot.Pokemon
{
    public enum Enumerations
    {
        WildArea,
        Route5,
    }

    public enum EncounterType
    {
        None = 0,
        Regis = 1,
        Regigigas = 2,
        Spiritomb = 3,
        SoJ = 4,
        Eternatus = 5,
        Keldeo = 6,
        Articuno = 7,
        Zapdos = 8,
        Moltres = 9,
        Wailord = 10,
        OverworldAny = 11,
    }

    public enum TargetShinyType
    {
        DisableOption,  // Doesn't care
        NonShiny,       // Match nonshiny only
        AnyShiny,       // Match any shiny regardless of type
        StarOnly,       // Match star shiny only
        SquareOnly,     // Match square shiny only
    }

    public enum LetsGoTest
    {
        TestOffsets,
        EscapeFromBattle,
        CheckTrades,
        CheckGifts,
        CheckGameOpen,
        CheckIsInBattle,
    }

    public enum MarkIndex
    {
        None = 0,   //Doesn't care
        Any = 1,    //Match any Mark regardless of which
        MarkLunchtime = 53,
        MarkSleepyTime = 54,
        MarkDusk = 55,
        MarkDawn = 56,
        MarkCloudy = 57,
        MarkRainy = 58,
        MarkStormy = 59,
        MarkSnowy = 60,
        MarkBlizzard = 61,
        MarkDry = 62,
        MarkSandstorm = 63,
        MarkMisty = 64,
        MarkDestiny = 65,
        MarkFishing = 66,
        MarkCurry = 67,
        MarkUncommon = 68,
        MarkRare = 69,
        MarkRowdy = 70,
        MarkAbsentMinded = 71,
        MarkJittery = 72,
        MarkExcited = 73,
        MarkCharismatic = 74,
        MarkCalmness = 75,
        MarkIntense = 76,
        MarkZonedOut = 77,
        MarkJoyful = 78,
        MarkAngry = 79,
        MarkSmiley = 80,
        MarkTeary = 81,
        MarkUpbeat = 82,
        MarkPeeved = 83,
        MarkIntellectual = 84,
        MarkFerocious = 85,
        MarkCrafty = 86,
        MarkScowling = 87,
        MarkKindly = 88,
        MarkFlustered = 89,
        MarkPumpedUp = 90,
        MarkZeroEnergy = 91,
        MarkPrideful = 92,
        MarkUnsure = 93,
        MarkHumble = 94,
        MarkThorny = 95,
        MarkVigor = 96,
        MarkSlump = 97
    }

    public enum LairSpecies : ushort
    {
        None = 0,
        Articuno = 144,
        Zapdos = 145,
        Moltres = 146,
        Mewtwo = 150,
        Raikou = 243,
        Entei = 244,
        Suicune = 245,
        Lugia = 249,
        HoOh = 250,
        Latias = 380,
        Latios = 381,
        Kyogre = 382,
        Groudon = 383,
        Rayquaza = 384,
        Uxie = 480,
        Mesprit = 481,
        Azelf = 482,
        Dialga = 483,
        Palkia = 484,
        Heatran = 485,
        Giratina = 487,
        Cresselia = 488,
        Tornadus = 641,
        Thundurus = 642,
        Landorus = 645,
        Reshiram = 643,
        Zekrom = 644,
        Kyurem = 646,
        Xerneas = 716,
        Yveltal = 717,
        Zygarde = 718,
        TapuKoko = 785,
        TapuLele = 786,
        TapuBulu = 787,
        TapuFini = 788,
        Solgaleo = 791,
        Lunala = 792,
        Nihilego = 793,
        Buzzwole = 794,
        Pheromosa = 795,
        Xurkitree = 796,
        Celesteela = 797,
        Kartana = 798,
        Guzzlord = 799,
        Necrozma = 800,
        Stakataka = 805,
        Blacephalon = 806
    }

    public enum Legendary : ushort
    {
        Articuno = 144,
        Zapdos = 145,
        Moltres = 146,
        Mewtwo = 150,
        Mew = 151,
        Raikou = 243,
        Entei = 244,
        Suicune = 245,
        Lugia = 249,
        HoOh = 250,
        Celebi = 251,
        Regirock = 377,
        Regice = 378,
        Registeel = 379,
        Latias = 380,
        Latios = 381,
        Kyogre = 382,
        Groudon = 383,
        Rayquaza = 384,
        Jirachi = 385,
        Deoxys = 386,
        Uxie = 480,
        Mesprit = 481,
        Azelf = 482,
        Dialga = 483,
        Palkia = 484,
        Heatran = 485,
        Regigigas = 486,
        Giratina = 487,
        Cresselia = 488,
        Phione = 489,
        Manaphy = 490,
        Darkrai = 491,
        Shaymin = 492,
        Arceus = 493,
        Victini = 494,
        Cobalion = 638,
        Terrakion = 639,
        Virizion = 640,
        Tornadus = 641,
        Thundurus = 642,
        Landorus = 645,
        Reshiram = 643,
        Zekrom = 644,
        Kyurem = 646,
        Keldeo = 647,
        Meloetta = 648,
        Genesect = 649,
        Xerneas = 716,
        Yveltal = 717,
        Zygarde = 718,
        Diancie = 719,
        Hoopa = 720,
        Volcanion = 721,
        TypeNull = 772,
        Silvally = 773,
        TapuKoko = 785,
        TapuLele = 786,
        TapuBulu = 787,
        TapuFini = 788,
        Cosmog = 789,
        Cosmoem = 790,
        Solgaleo = 791,
        Lunala = 792,
        Nihilego = 793,
        Buzzwole = 794,
        Pheromosa = 795,
        Xurkitree = 796,
        Celesteela = 797,
        Kartana = 798,
        Guzzlord = 799,
        Necrozma = 800,
        Magearna = 801,
        Marshadow = 802,
        Poipole = 803,
        Naganadel = 804,
        Stakataka = 805,
        Blacephalon = 806,
        Zeraora = 807,
        Meltan = 808,
        Melmetal = 809,
        Zacian = 888,
        Zamazenta = 889,
        Eternatus = 890,
        Kubfu = 891,
        Urshifu = 892,
        Zarude = 893,
        Regieleki = 894,
        Regidrago = 895,
        Glastrier = 896,
        Spectrier = 897,
        Calyrex = 898
    }
    
}
